name: Run Unit Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps: 
      - name: Set up Go 1.22.2
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22.2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Start Monogodb
        run: docker run -d -p 27017:27017 mongo:5.0
      
      - name: Create .env file
        run: |
          echo DB_SOURCE=mongodb://localhost:27017 >> .env

      - name: Test 
        run: go test -v -count=1 ./...
